# Generated by Django 4.1 on 2022-08-17 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="keywords",
            options={"verbose_name": "Key Word", "verbose_name_plural": "Key Words"},
        ),
        migrations.AlterModelOptions(
            name="postobject",
            options={"verbose_name": "Post", "verbose_name_plural": "Posts"},
        ),
        migrations.AlterModelOptions(
            name="type",
            options={"verbose_name": "Type", "verbose_name_plural": "Types"},
        ),
        migrations.AddField(
            model_name="postobject",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
